Fix styles
devballteam/healthcheckMonitoring pull request #1
Opened 2019-03-29 10:33 UTC by mpietrowiak

2019-03-29 10:34 UTC, marekbogatzki approved these changes

2019-04-01 11:27 UTC, esuszek requested changes
Could you change the commit message - please add a ticket number if you have some.

2019-04-01 11:27 UTC, esuszek commented on public/styles.css
> +  list-style: none;
alphabetical order, please.

2019-04-02 13:49 UTC, mpietrowiak commented on public/styles.css
> +  list-style: none;
done

2019-04-03 09:14 UTC, marekbogatzki approved these changes

2019-04-04 07:07 UTC, esuszek approved these changes

2019-04-04 23:23 UTC, tomaszharazin approved these changes

2019-04-15 06:10 UTC, marekbogatzki approved these changes

2019-04-15 08:42 UTC, merged